### ISSUE TITLE
Does connect, beeps, yet actions have no impact (start, speed, etc)

### ISSUE THREAD

**Issue by Utopiah** [ph4r05/ph4-walkingpad#10]
Hi,

just stumble upon your amazing project via https://huserben.github.io/Automating-Walkingpad/ and with the hope of continuing my home automation process and tinkering (safely) with VR physical activity.

Anyway I manage to connect, ysing `ph4-walkingpad-ctl --stats 750 --json-file ~/walking.json`, as least as I assume from the beeping sound coming from the device, but unfortunately commands do not seem to work.

I tried with `--debug` which gives me the error `INFO Error in ask stats: Task <Task pending name='Task-5' coro=<WalkingPadControl.stats_fetcher()`. See part of the log below : 

```
2022-08-17 15:26:31 fabien-CORSAIR-ONE-i160 ph4_walkingpad.pad[739255] INFO Service enumeration done
2022-08-17 15:26:33 fabien-CORSAIR-ONE-i160 bleak.backends.bluezdbus.client[739255] DEBUG Write Characteristic 0000fe02-0000-1000-8000-00805f9b34fb | /org/bluez/hci0/dev_57_4C_4E_11_79_0C/service0013/char0017: bytearray(b'\xf7\xa5`JM\x93q)\xc9\xfd')
2022-08-17 15:26:33 fabien-CORSAIR-ONE-i160 bleak.backends.bluezdbus.manager[739255] DEBUG received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_57_4C_4E_11_79_0C/service0013/char0014): ['org.bluez.GattCharacteristic1', {'Value': <dbus_next.signature.Variant ('ay', b'\xf8\xa5MP1\x12\n\xb4\n\x00\x01\x00\x00!s\x18\x00\x00\xfa\xfd')>}, []]
2022-08-17 15:26:33 fabien-CORSAIR-ONE-i160 ph4_walkingpad.pad[739255] DEBUG Msg: f8, a5, 4d, 50, 31, 12, 0a, b4, 0a, 00, 01, 00, 00, 21, 73, 18, 00, 00, fa, fd
2022-08-17 15:26:34 fabien-CORSAIR-ONE-i160 bleak.backends.bluezdbus.client[739255] DEBUG Write Characteristic 0000fe02-0000-1000-8000-00805f9b34fb | /org/bluez/hci0/dev_57_4C_4E_11_79_0C/service0013/char0017: bytearray(b'\xf7\xa2\x03\x07\xac\xfd')
2022-08-17 15:26:34 fabien-CORSAIR-ONE-i160 bleak.backends.bluezdbus.manager[739255] DEBUG received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_57_4C_4E_11_79_0C/service0013/char0014): ['org.bluez.GattCharacteristic1', {'Value': <dbus_next.signature.Variant ('ay', b'\xf8\xa2\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x07\x00\x00\x00\xaa\xfd')>}, []]
2022-08-17 15:26:34 fabien-CORSAIR-ONE-i160 ph4_walkingpad.pad[739255] DEBUG Msg: f8, a2, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 07, 00, 00, 00, aa, fd
WalkingPadCurStatus(dist=0.0, time=0, steps=0, speed=0.0, state=0, mode=1, app_speed=0.23333333333333334, button=1, rest=0000)
2022-08-17 15:26:34 fabien-CORSAIR-ONE-i160 ph4_walkingpad.pad[739255] DEBUG Status: WalkingPadCurStatus(dist=0.0, time=0, steps=0, speed=0.0, state=0, mode=1, app_speed=0.23333333333333334, button=1, rest=0000)
2022-08-17 15:26:35 fabien-CORSAIR-ONE-i160 asyncio[739255] DEBUG Using selector: EpollSelector
2022-08-17 15:26:35 fabien-CORSAIR-ONE-i160 ph4_walkingpad.cmd_helper[739255] DEBUG Starting looper for loop <_UnixSelectorEventLoop running=False closed=False debug=False>
2022-08-17 15:26:35 fabien-CORSAIR-ONE-i160 ph4_walkingpad.main[739255] INFO Starting stats fetching
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    WalkingPad controller

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
2022-08-17 15:26:35 fabien-CORSAIR-ONE-i160 ph4_walkingpad.main[739255] INFO Error in ask stats: Task <Task pending name='Task-5' coro=<WalkingPadControl.stats_fetcher() running at /home/fabien/.local/lib/python3.10/site-packages/ph4_walkingpad/main.py:171> cb=[_chain_future.<locals>._call_set_state() at /usr/lib/python3.10/asyncio/futures.py:391]> got Future <Future pending created at /usr/lib/python3.10/asyncio/base_events.py:429> attached to a different loop
```

I'm not sure what model I have as I never used the app (privacy concerns) and only the remote. If that helps I could install it and check.

Otherwise here are the details : 

![image](https://user-images.githubusercontent.com/1076655/185147302-8307bd10-db97-40fb-860a-752078f42240.png)

It's another brand but seems like the same device.

**Comment by ph4r05** [comment]
Thanks for the report @Utopiah! The error seems to be related to the implementation itself rather than belt model.

Which python version do you use? I would recommend trying Python 3.7 (e.g. with https://github.com/pyenv/pyenv)

**Comment by Utopiah** [comment]
I'm on `Python 3.10.4` the default for Ubuntu 22.04 AFAIK. Thanks for the prompt feedback, I'll try with 3.7 then and report back.

**Comment by Utopiah** [comment]
Neat, some progress but still no motion : 

```
fabien@fabien-CORSAIR-ONE-i160:~/Prototypes/walkingpad$ pyenv local 3.8.13
fabien@fabien-CORSAIR-ONE-i160:~/Prototypes/walkingpad$ ph4-walkingpad-ctl 
WalkingPadCurStatus(dist=0.0, time=0, steps=0, speed=0.0, state=0, mode=1, app_speed=0.23333333333333334, button=1, rest=0000)
------------------------------------------------------------------------------------------------------------------------------------------------------------------
    WalkingPad controller

------------------------------------------------------------------------------------------------------------------------------------------------------------------
$> start
$> speed 30
$> start
$> status
WalkingPadCurStatus(dist=0.0, time=0, steps=0, speed=0.0, state=0, mode=1, app_speed=0.03333333333333333, button=1, rest=0000)
$> help

Documented commands (use 'help -v' for verbose/'help <topic>' for details):
===========================================================================
alias      edit     macro    q             s          speed   switch_mode
ask_beep   help     profile  quit          set        start   tasks      
ask_last   history  py       run_pyscript  shell      status  upload     
ask_stats  login    Q        run_script    shortcuts  stop  

Undocumented commands:
======================
margins

$> switch_mode
Unknown mode: . Supported: manual, auto, standby
$> switch_mode manual
$> start
$> speed 10
$> speed 20
$> ask_last
$> WalkingPadLastStatus(dist=0.0, time=0, steps=0, rest=000000000000)
```

PS: switch from 3.7 to 3.8 as somehow there was a problem with _curses

**Comment by Utopiah** [comment]
FWIW here are some `--debug` logs. I didn't attach because I couldn't figure out any error but might still help : 

```
2022-08-19 14:43:51 fabien-CORSAIR-ONE-i160 bleak.backends.bluezdbus.manager[1009552] DEBUG received D-Bus signal: org.freedesktop.DBus.ObjectManager.InterfacesRemoved (/): ['/org/bluez/hci0/dev_1F_68_C9_3F_96_9F', ['org.freedesktop.DBus.Properties', 'org.freedesktop.DBus.Introspectable', 'org.bluez.Device1']]
2022-08-19 14:43:52 fabien-CORSAIR-ONE-i160 bleak.backends.bluezdbus.manager[1009552] DEBUG received D-Bus signal: org.freedesktop.DBus.ObjectManager.InterfacesRemoved (/): ['/org/bluez/hci0/dev_63_E5_C8_E8_78_44', ['org.freedesktop.DBus.Properties', 'org.freedesktop.DBus.Introspectable', 'org.bluez.Device1']]
2022-08-19 14:43:53 fabien-CORSAIR-ONE-i160 bleak.backends.bluezdbus.manager[1009552] DEBUG received D-Bus signal: org.freedesktop.DBus.ObjectManager.InterfacesRemoved (/): ['/org/bluez/hci0/dev_90_DD_5D_B9_BD_41', ['org.freedesktop.DBus.Properties', 'org.freedesktop.DBus.Introspectable', 'org.bluez.Device1']]
2022-08-19 14:43:53 fabien-CORSAIR-ONE-i160 bleak.backends.bluezdbus.manager[1009552] DEBUG received D-Bus signal: org.freedesktop.DBus.ObjectManager.InterfacesRemoved (/): ['/org/bluez/hci0/dev_2C_26_17_0B_3B_77', ['org.freedesktop.DBus.Properties', 'org.freedesktop.DBus.Introspectable', 'org.bluez.Device1']]
2022-08-19 14:43:53 fabien-CORSAIR-ONE-i160 bleak.backends.bluezdbus.manager[1009552] DEBUG received D-Bus signal: org.freedesktop.DBus.ObjectManager.InterfacesRemoved (/): ['/org/bluez/hci0/dev_C6_5D_DC_F8_4F_11', ['org.freedesktop.DBus.Properties', 'org.freedesktop.DBus.Introspectable', 'org.bluez.Device1']]
2022-08-19 14:43:53 fabien-CORSAIR-ONE-i160 bleak.backends.bluezdbus.manager[1009552] DEBUG received D-Bus signal: org.freedesktop.DBus.ObjectManager.InterfacesRemoved (/): ['/org/bluez/hci0/dev_D0_50_3C_12_BE_2F', ['org.freedesktop.DBus.Properties', 'org.freedesktop.DBus.Introspectable', 'org.bluez.Device1']]
status
WalkingPadCurStatus(dist=0.0, time=0, steps=0, speed=0.0, state=0, mode=1, app_speed=0.03333333333333333, button=1, rest=0000)
$> help

Documented commands (use 'help -v' for verbose/'help <topic>' for details):
===========================================================================
alias      edit     macro    q             s          speed   switch_mode
ask_beep   help     profile  quit          set        start   tasks      
ask_last   history  py       run_pyscript  shell      status  upload     
ask_stats  login    Q        run_script    shortcuts  stop  

Undocumented commands:
======================
margins

$> switch_mode 
Unknown mode: . Supported: manual, auto, standby
$> switch_mode manual
$> 2022-08-19 14:44:17 fabien-CORSAIR-ONE-i160 bleak.backends.bluezdbus.manager[1009552] DEBUG received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_57_4C_4E_11_79_0C/service0013/char0014): ['org.bluez.GattCharacteristic1', {'Value': <dbus_next.signature.Variant ('ay', b'\xf8\xa2\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\xa4\xfd')>}, []]
2022-08-19 14:44:17 fabien-CORSAIR-ONE-i160 ph4_walkingpad.pad[1009552] DEBUG Msg: f8, a2, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 01, 00, 00, 00, a4, fd
2022-08-19 14:44:17 fabien-CORSAIR-ONE-i160 ph4_walkingpad.pad[1009552] DEBUG Status: WalkingPadCurStatus(dist=0.0, time=0, steps=0, speed=0.0, state=0, mode=1, app_speed=0.03333333333333333, button=1, rest=0000)
status
WalkingPadCurStatus(dist=0.0, time=0, steps=0, speed=0.0, state=0, mode=1, app_speed=0.03333333333333333, button=1, rest=0000)
$> switch_mode auto
$> 2022-08-19 14:44:37 fabien-CORSAIR-ONE-i160 bleak.backends.bluezdbus.manager[1009552] DEBUG received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_57_4C_4E_11_79_0C/service0013/char0014): ['org.bluez.GattCharacteristic1', {'Value': <dbus_next.signature.Variant ('ay', b'\xf8\xa2\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa2\xfd')>}, []]
2022-08-19 14:44:37 fabien-CORSAIR-ONE-i160 ph4_walkingpad.pad[1009552] DEBUG Msg: f8, a2, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, a2, fd
2022-08-19 14:44:37 fabien-CORSAIR-ONE-i160 ph4_walkingpad.pad[1009552] DEBUG Status: WalkingPadCurStatus(dist=0.0, time=0, steps=0, speed=0.0, state=0, mode=0, app_speed=0, button=0, rest=0000)
status
WalkingPadCurStatus(dist=0.0, time=0, steps=0, speed=0.0, state=0, mode=0, app_speed=0, button=0, rest=0000)
$> start
$> 2022-08-19 14:44:42 fabien-CORSAIR-ONE-i160 bleak.backends.bluezdbus.manager[1009552] DEBUG received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_57_4C_4E_11_79_0C/service0013/char0014): ['org.bluez.GattCharacteristic1', {'Value': <dbus_next.signature.Variant ('ay', b'\xf8\xa2\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\xa4\xfd')>}, []]
2022-08-19 14:44:42 fabien-CORSAIR-ONE-i160 ph4_walkingpad.pad[1009552] DEBUG Msg: f8, a2, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 01, 00, 00, 00, a4, fd
2022-08-19 14:44:42 fabien-CORSAIR-ONE-i160 ph4_walkingpad.pad[1009552] DEBUG Status: WalkingPadCurStatus(dist=0.0, time=0, steps=0, speed=0.0, state=0, mode=1, app_speed=0.03333333333333333, button=1, rest=0000)
speed 10
$> 2022-08-19 14:44:48 fabien-CORSAIR-ONE-i160 bleak.backends.bluezdbus.manager[1009552] DEBUG received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_57_4C_4E_11_79_0C/service0013/char0014): ['org.bluez.GattCharacteristic1', {'Value': <dbus_next.signature.Variant ('ay', b'\xf8\xa2\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1e\x00\x00\x00\xc1\xfd')>}, []]
2022-08-19 14:44:48 fabien-CORSAIR-ONE-i160 ph4_walkingpad.pad[1009552] DEBUG Msg: f8, a2, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 1e, 00, 00, 00, c1, fd
2022-08-19 14:44:48 fabien-CORSAIR-ONE-i160 ph4_walkingpad.pad[1009552] DEBUG Status: WalkingPadCurStatus(dist=0.0, time=0, steps=0, speed=0.0, state=0, mode=1, app_speed=1.0, button=1, rest=0000)
speed 20
$> 2022-08-19 14:44:54 fabien-CORSAIR-ONE-i160 bleak.backends.bluezdbus.manager[1009552] DEBUG received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_57_4C_4E_11_79_0C/service0013/char0014): ['org.bluez.GattCharacteristic1', {'Value': <dbus_next.signature.Variant ('ay', b'\xf8\xa2\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00<\x00\x00\x00\xdf\xfd')>}, []]
2022-08-19 14:44:54 fabien-CORSAIR-ONE-i160 ph4_walkingpad.pad[1009552] DEBUG Msg: f8, a2, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 3c, 00, 00, 00, df, fd
2022-08-19 14:44:54 fabien-CORSAIR-ONE-i160 ph4_walkingpad.pad[1009552] DEBUG Status: WalkingPadCurStatus(dist=0.0, time=0, steps=0, speed=0.0, state=0, mode=1, app_speed=2.0, button=1, rest=0000)
start
$> 2022-08-19 14:44:59 fabien-CORSAIR-ONE-i160 bleak.backends.bluezdbus.manager[1009552] DEBUG received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_57_4C_4E_11_79_0C/service0013/char0014): ['org.bluez.GattCharacteristic1', {'Value': <dbus_next.signature.Variant ('ay', b'\xf8\xa2\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\xa4\xfd')>}, []]
2022-08-19 14:44:59 fabien-CORSAIR-ONE-i160 ph4_walkingpad.pad[1009552] DEBUG Msg: f8, a2, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 01, 00, 00, 00, a4, fd
2022-08-19 14:44:59 fabien-CORSAIR-ONE-i160 ph4_walkingpad.pad[1009552] DEBUG Status: WalkingPadCurStatus(dist=0.0, time=0, steps=0, speed=0.0, state=0, mode=1, app_speed=0.03333333333333333, button=1, rest=0000)
history
    1  start
    2  status
    3  help
    4  switch_mode
    5  switch_mode manual
    6  status
    7  switch_mode auto
    8  status
    9  start
   10  speed 10
   11  speed 20
   12  start
$> ask_last
$> 2022-08-19 14:45:07 fabien-CORSAIR-ONE-i160 bleak.backends.bluezdbus.manager[1009552] DEBUG received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_57_4C_4E_11_79_0C/service0013/char0014): ['org.bluez.GattCharacteristic1', {'Value': <dbus_next.signature.Variant ('ay', b'\xf8\xa7\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa7\xfd')>}, []]
2022-08-19 14:45:07 fabien-CORSAIR-ONE-i160 ph4_walkingpad.pad[1009552] DEBUG Msg: f8, a7, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, a7, fd
WalkingPadLastStatus(dist=0.0, time=0, steps=0, rest=000000000000)
2022-08-19 14:45:07 fabien-CORSAIR-ONE-i160 ph4_walkingpad.pad[1009552] DEBUG Record: WalkingPadLastStatus(dist=0.0, time=0, steps=0, rest=000000000000)
login
Logging in...
2022-08-19 14:45:14 fabien-CORSAIR-ONE-i160 ph4_walkingpad.main[1009552] ERROR Could not login: Could not login, no profile
Traceback (most recent call last):
  File "/home/fabien/.local/lib/python3.10/site-packages/ph4_walkingpad/main.py", line 608, in do_login
    r = self.login()
  File "/home/fabien/.local/lib/python3.10/site-packages/ph4_walkingpad/main.py", line 294, in login
    raise ValueError('Could not login, no profile')
ValueError: Could not login, no profile
$> tasks
EXCEPTION of type 'AttributeError' occurred with message: 'type object '_asyncio.Task' has no attribute 'all_tasks''
To enable full traceback, run the following command: 'set debug true'
$> stop
$> 2022-08-19 14:45:33 fabien-CORSAIR-ONE-i160 bleak.backends.bluezdbus.manager[1009552] DEBUG received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_57_4C_4E_11_79_0C/service0013/char0014): ['org.bluez.GattCharacteristic1', {'Value': <dbus_next.signature.Variant ('ay', b'\xf8\xa2\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa3\xfd')>}, []]
2022-08-19 14:45:33 fabien-CORSAIR-ONE-i160 ph4_walkingpad.pad[1009552] DEBUG Msg: f8, a2, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, a3, fd
2022-08-19 14:45:33 fabien-CORSAIR-ONE-i160 ph4_walkingpad.pad[1009552] DEBUG Status: WalkingPadCurStatus(dist=0.0, time=0, steps=0, speed=0.0, state=0, mode=1, app_speed=0, button=1, rest=0000)
start
$> 2022-08-19 14:45:35 fabien-CORSAIR-ONE-i160 bleak.backends.bluezdbus.manager[1009552] DEBUG received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_57_4C_4E_11_79_0C/service0013/char0014): ['org.bluez.GattCharacteristic1', {'Value': <dbus_next.signature.Variant ('ay', b'\xf8\xa2\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\xa4\xfd')>}, []]
2022-08-19 14:45:35 fabien-CORSAIR-ONE-i160 ph4_walkingpad.pad[1009552] DEBUG Msg: f8, a2, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 01, 00, 00, 00, a4, fd
2022-08-19 14:45:35 fabien-CORSAIR-ONE-i160 ph4_walkingpad.pad[1009552] DEBUG Status: WalkingPadCurStatus(dist=0.0, time=0, steps=0, speed=0.0, state=0, mode=1, app_speed=0.03333333333333333, button=1, rest=0000)
speed 30
$> 2022-08-19 14:45:40 fabien-CORSAIR-ONE-i160 bleak.backends.bluezdbus.manager[1009552] DEBUG received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_57_4C_4E_11_79_0C/service0013/char0014): ['org.bluez.GattCharacteristic1', {'Value': <dbus_next.signature.Variant ('ay', b'\xf8\xa2\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00Z\x00\x00\x00\xfd\xfd')>}, []]
2022-08-19 14:45:40 fabien-CORSAIR-ONE-i160 ph4_walkingpad.pad[1009552] DEBUG Msg: f8, a2, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 5a, 00, 00, 00, fd, fd
2022-08-19 14:45:40 fabien-CORSAIR-ONE-i160 ph4_walkingpad.pad[1009552] DEBUG Status: WalkingPadCurStatus(dist=0.0, time=0, steps=0, speed=0.0, state=0, mode=1, app_speed=3.0, button=1, rest=0000)
start
$> 2022-08-19 14:45:42 fabien-CORSAIR-ONE-i160 bleak.backends.bluezdbus.manager[1009552] DEBUG received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_57_4C_4E_11_79_0C/service0013/char0014): ['org.bluez.GattCharacteristic1', {'Value': <dbus_next.signature.Variant ('ay', b'\xf8\xa2\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\xa4\xfd')>}, []]
2022-08-19 14:45:42 fabien-CORSAIR-ONE-i160 ph4_walkingpad.pad[1009552] DEBUG Msg: f8, a2, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 01, 00, 00, 00, a4, fd
2022-08-19 14:45:42 fabien-CORSAIR-ONE-i160 ph4_walkingpad.pad[1009552] DEBUG Status: WalkingPadCurStatus(dist=0.0, time=0, steps=0, speed=0.0, state=0, mode=1, app_speed=0.03333333333333333, button=1, rest=0000)
stop
$> 2022-08-19 14:45:44 fabien-CORSAIR-ONE-i160 bleak.backends.bluezdbus.manager[1009552] DEBUG received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_57_4C_4E_11_79_0C/service0013/char0014): ['org.bluez.GattCharacteristic1', {'Value': <dbus_next.signature.Variant ('ay', b'\xf8\xa2\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa3\xfd')>}, []]
2022-08-19 14:45:44 fabien-CORSAIR-ONE-i160 ph4_walkingpad.pad[1009552] DEBUG Msg: f8, a2, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, 00, a3, fd
2022-08-19 14:45:44 fabien-CORSAIR-ONE-i160 ph4_walkingpad.pad[1009552] DEBUG Status: WalkingPadCurStatus(dist=0.0, time=0, steps=0, speed=0.0, state=0, mode=1, app_speed=0, button=1, rest=0000)
start
$> 2022-08-19 14:45:45 fabien-CORSAIR-ONE-i160 bleak.backends.bluezdbus.manager[1009552] DEBUG received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_57_4C_4E_11_79_0C/service0013/char0014): ['org.bluez.GattCharacteristic1', {'Value': <dbus_next.signature.Variant ('ay', b'\xf8\xa2\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\xa4\xfd')>}, []]
2022-08-19 14:45:45 fabien-CORSAIR-ONE-i160 ph4_walkingpad.pad[1009552] DEBUG Msg: f8, a2, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 01, 00, 00, 00, a4, fd
2022-08-19 14:45:45 fabien-CORSAIR-ONE-i160 ph4_walkingpad.pad[1009552] DEBUG Status: WalkingPadCurStatus(dist=0.0, time=0, steps=0, speed=0.0, state=0, mode=1, app_speed=0.03333333333333333, button=1, rest=0000)
start
$> 2022-08-19 14:45:48 fabien-CORSAIR-ONE-i160 bleak.backends.bluezdbus.manager[1009552] DEBUG received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_57_4C_4E_11_79_0C/service0013/char0014): ['org.bluez.GattCharacteristic1', {'Value': <dbus_next.signature.Variant ('ay', b'\xf8\xa2\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\xa4\xfd')>}, []]
2022-08-19 14:45:48 fabien-CORSAIR-ONE-i160 ph4_walkingpad.pad[1009552] DEBUG Msg: f8, a2, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 01, 00, 00, 00, a4, fd
2022-08-19 14:45:48 fabien-CORSAIR-ONE-i160 ph4_walkingpad.pad[1009552] DEBUG Status: WalkingPadCurStatus(dist=0.0, time=0, steps=0, speed=0.0, state=0, mode=1, app_speed=0.03333333333333333, button=1, rest=0000)
switch_mode
Unknown mode: . Supported: manual, auto, standby
$> switch_mode standby
$> 2022-08-19 14:46:02 fabien-CORSAIR-ONE-i160 bleak.backends.bluezdbus.manager[1009552] DEBUG received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_57_4C_4E_11_79_0C/service0013/char0014): ['org.bluez.GattCharacteristic1', {'Value': <dbus_next.signature.Variant ('ay', b'\xf8\xa2\x05\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\xab\xfd')>}, []]
2022-08-19 14:46:02 fabien-CORSAIR-ONE-i160 ph4_walkingpad.pad[1009552] DEBUG Msg: f8, a2, 05, 00, 02, 00, 00, 00, 00, 00, 00, 00, 00, 00, 02, 00, 00, 00, ab, fd
2022-08-19 14:46:02 fabien-CORSAIR-ONE-i160 ph4_walkingpad.pad[1009552] DEBUG Status: WalkingPadCurStatus(dist=0.0, time=0, steps=0, speed=0.0, state=5, mode=2, app_speed=0.06666666666666667, button=2, rest=0000)
start
$> 2022-08-19 14:46:04 fabien-CORSAIR-ONE-i160 bleak.backends.bluezdbus.manager[1009552] DEBUG received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_57_4C_4E_11_79_0C/service0013/char0014): ['org.bluez.GattCharacteristic1', {'Value': <dbus_next.signature.Variant ('ay', b'\xf8\xa2\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\xa4\xfd')>}, []]
2022-08-19 14:46:04 fabien-CORSAIR-ONE-i160 ph4_walkingpad.pad[1009552] DEBUG Msg: f8, a2, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 01, 00, 00, 00, a4, fd
2022-08-19 14:46:04 fabien-CORSAIR-ONE-i160 ph4_walkingpad.pad[1009552] DEBUG Status: WalkingPadCurStatus(dist=0.0, time=0, steps=0, speed=0.0, state=0, mode=1, app_speed=0.03333333333333333, button=1, rest=0000)
```

Looks like the commands are receive because `mode` and `app_speed` do change but somehow no physical consequence.

**Comment by ph4r05** [comment]
@Utopiah thanks for more info! Is the ph4-walkingpad receiving stats correctly? Can you see walking progress / are stats stored to a file?

If changing python version helps and command is actually send and received by the belt (audible beep), it may be the case your belt has different comm protocol that the one I was using. If this is the case, there is, unfortunately, nothing I can do. 

But, you can try downloading an official belt app, attaching `adb` debugger (android phone only) and capture commands that app is using to communicate with the belt from the app log. More on this: https://github.com/ph4r05/ph4-walkingpad#reversing-belt-api

**Comment by Utopiah** [comment]
Was worried it might be the case. I don't have an Android phone right now but would Waydroid https://github.com/waydroid/waydroid potentially work?

**Comment by ph4r05** [comment]
@Utopiah thanks for more info! Is the ph4-walkingpad receiving stats correctly? Can you see walking progress / are stats stored to a file?

If changing python version helps and command is actually send and received by the belt (audible beep), it may be the case your belt has different comm protocol that the one I was using. If this is the case, there is, unfortunately, nothing I can do. 

But, you can try downloading an official belt app, attaching `adb` debugger (android phone only) and capture commands that app is using to communicate with the belt from the app log. More on this: https://github.com/ph4r05/ph4-walkingpad#reversing-belt-api

**Comment by Johni0702** [comment]
I believe I may be running into the same issue with a regular Walkingpad P1: Everything (including stats) appears to be working, the belt beeps once in response to commands, but it doesn't actually start moving.

After a few hours of debugging (because I half assumed that there were minor protocol differences), it appears that this may still be an implementation issue (mine at least is, can't be sure about OP ofc).
The giveaway, and also the reason I strongly suspect it's the same issue, is that after the `start` command, only one response is received:
```
start
$> 2022-08-19 14:45:42 fabien-CORSAIR-ONE-i160 bleak.backends.bluezdbus.manager[1009552] DEBUG received D-Bus signal: org.freedesktop.DBus.Properties.PropertiesChanged (/org/bluez/hci0/dev_57_4C_4E_11_79_0C/service0013/char0014): ['org.bluez.GattCharacteristic1', {'Value': <dbus_next.signature.Variant ('ay', b'\xf8\xa2\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\xa4\xfd')>}, []]
2022-08-19 14:45:42 fabien-CORSAIR-ONE-i160 ph4_walkingpad.pad[1009552] DEBUG Msg: f8, a2, 00, 00, 01, 00, 00, 00, 00, 00, 00, 00, 00, 00, 01, 00, 00, 00, a4, fd
2022-08-19 14:45:42 fabien-CORSAIR-ONE-i160 ph4_walkingpad.pad[1009552] DEBUG Status: WalkingPadCurStatus(dist=0.0, time=0, steps=0, speed=0.0, state=0, mode=1, app_speed=0.03333333333333333, button=1, rest=0000)
```
despite `start_belt` sending two commands:
```python
    async def start_belt(self, manual=True):
        if manual:
            await self.ctler.switch_mode(WalkingPad.MODE_MANUAL)
            await asyncio.sleep(1.5)
            await self.ctler.start_belt()
        else:
            await self.ctler.switch_mode(WalkingPad.MODE_AUTOMAT)
            await asyncio.sleep(1.5)
            await self.ctler.start_belt()
```
and indeed, adding some logging shows that the coroutine never even makes it to the `sleep` line, let alone the second command. And given the second command is the one that actually starts the belt, the fact that it doesn't physically start isn't surprising any more.
I suspect it's something to do with how there are two (three with stats recording) different event loops because
- Across a two digit number of attempts, it did randomly just work once, suggesting it's some kind of race condition?
- If I set `worker_loop` and `stats_loop` to `asyncio.get_current_loop()` instead of creating a new loop+thread each (so there's only the main thread loop), it suddenly starts working reliably with seemingly no issue (also fixes the "Error in ask stats: Task X got Future Y attached to a different loop" error spam mentioned in the initial post).

Unfortunately I'm not really familiar with Python's async stuff and don't understand why ph4-walkingpad is starting two extra loops in the first place, so I don't know how to proceed from here.
If there's anything you need to know or want me to test, let me know.

Tried mostly with Python 3.10.11 but also some with 3.8.16 and 3.7.16 with no apparent difference.
