### ISSUE TITLE
Exception raised after connection

### ISSUE THREAD

**Issue by linkspec** [ph4r05/ph4-walkingpad#15]
It appears that I'm successfully connecting to the device, however immediately that I get a status output and the 'menu' appears, I then get the below exception.

Behavior appears to be the same regardless of whether I manually specify the MAC or not. Python is version 3.12.0

`(.venv) PS D:\Documents\Python\treadmil> ph4-walkingpad-ctl --stats 750 --json-file walking2.json -a 57:4C:4E:2B:25:FC 
WalkingPadCurStatus(dist=0.0, time=0, steps=0, speed=0.0, state=0, mode=1, app_speed=0.23333333333333334, button=1, rest=0000)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    WalkingPad controller

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
2024-03-24 17:08:18 JamesPC ph4_walkingpad.main[18276] ERROR Exception in the main entry point:
Traceback (most recent call last):
  File "D:\Documents\Python\treadmil\.venv\Lib\site-packages\ph4_walkingpad\main.py", line 375, in main
    await self.work()
  File "D:\Documents\Python\treadmil\.venv\Lib\site-packages\ph4_walkingpad\main.py", line 104, in work
    res = await self.entry()
          ^^^^^^^^^^^^^^^^^^
  File "D:\Documents\Python\treadmil\.venv\Lib\site-packages\ph4_walkingpad\main.py", line 188, in entry
    await self.acmdloop()
  File "D:\Documents\Python\treadmil\.venv\Lib\site-packages\ph4acmd2\__init__.py", line 153, in acmdloop
    await self._acmdloop()
  File "D:\Documents\Python\treadmil\.venv\Lib\site-packages\ph4acmd2\__init__.py", line 181, in _acmdloop
    self._start_controller()
  File "D:\Documents\Python\treadmil\.venv\Lib\site-packages\ph4acmd2\__init__.py", line 51, in _start_controller
    self._start_reader()
  File "D:\Documents\Python\treadmil\.venv\Lib\site-packages\ph4acmd2\__init__.py", line 80, in _start_reader
    self.reset_reader()
  File "D:\Documents\Python\treadmil\.venv\Lib\site-packages\ph4acmd2\__init__.py", line 86, in reset_reader
    self.loop.add_reader(self.stdin.fileno(), self.reader)
  File "C:\Program Files\Python312\Lib\asyncio\events.py", line 534, in add_reader
    raise NotImplementedError
NotImplementedError`

**Comment by ph4r05** [comment]
Pls try now v1.0.2
