### ISSUE TITLE
R1 Pro - AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by ValonVN0** [ph4r05/ph4-walkingpad#17]
Hey there,

I know this project is more for the WalkingPad A1 however as you mention it seems the R1 Pro works under a similar setup.

Unfortunately I'm hitting this barrier upon trying to run

```ph4-walkingpad-ctl --stats 750 --json-file ~/walking.json```

```
C:\Users\xxxxxxxx>ph4-walkingpad-ctl --stats 750 --json-file ~/walking.json
C:\Users\xxxxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\ph4_walkingpad\pad.py:74: FutureWarning: BLEDevice.metadata is deprecated and will be removed in a future version of Bleak, use AdvertisementData instead
  info_str = ', '.join(["[%2d]" % i, str(dev[i].address), str(dev[i].name), str(dev[i].metadata["uuids"])])
C:\Users\xxxxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\ph4_walkingpad\pad.py:80: FutureWarning: BLEDevice.metadata is deprecated and will be removed in a future version of Bleak, use AdvertisementData instead
  self.devices_dict[dev[i].address].append(dev[i].metadata["uuids"])
2024-08-29 16:05:48 DESKTOP-130LB3O ph4_walkingpad.main[8752] ERROR Exception in the main entry point: 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "C:\Users\xxxxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\ph4_walkingpad\main.py", line 375, in main
    await self.work()
  File "C:\Users\xxxxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\ph4_walkingpad\main.py", line 91, in work
    address = await self.scan_address()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\ph4_walkingpad\main.py", line 135, in scan_address
    await scanner.scan(timeout=self.args.scan_timeout)
  File "C:\Users\xxxxxxxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\ph4_walkingpad\pad.py", line 83, in scan
    if dev_name and dev_name in dev[i].name.lower():
                                ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'
```

I'd assume this means it's unable to find the device however I'm not too sure what my options are. I've ensured it's not already connected to the phone so that shouldn't be the issue.

**Comment by jure123** [comment]
There is a bug in the code. In file ph4-walkingpad/pad.py modify line 83: 

from:
`if dev_name and dev_name in dev[i].name.lower():`

to:
`if dev_name and dev[i].name and dev_name in dev[i].name.lower():`

Apparently some found bluetooth devices don't have name attribute, that's why the original code fails.

**Comment by dolomitt** [comment]
I have R1 pro too. same issue with bluetooth devices that have no name. the bluetooth device that works for me is named "RE". But it wont work very long.

```
2024-09-20 08:56:38 JFBZRL3 __main__[41856] INFO Starting stats fetching
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    WalkingPad controller

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
2024-09-20 08:56:38 JFBZRL3 asyncio[41856] DEBUG Using proactor: IocpProactor
2024-09-20 08:56:38 JFBZRL3 __main__[41856] ERROR Exception in the main entry point:
Traceback (most recent call last):
  File "C:\Users\tgravran\Documents\Development\python\ph4-walkingpad\ph4_walkingpad\main.py", line 375, in main
    await self.work()
  File "C:\Users\tgravran\Documents\Development\python\ph4-walkingpad\ph4_walkingpad\main.py", line 104, in work
    res = await self.entry()
          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\tgravran\Documents\Development\python\ph4-walkingpad\ph4_walkingpad\main.py", line 188, in entry
    await self.acmdloop()
  File "C:\Users\tgravran\AppData\Local\Programs\Python\Python312\Lib\site-packages\ph4acmd2\__init__.py", line 153, in acmdloop
    await self._acmdloop()
  File "C:\Users\tgravran\AppData\Local\Programs\Python\Python312\Lib\site-packages\ph4acmd2\__init__.py", line 181, in _acmdloop
    self._start_controller()
  File "C:\Users\tgravran\AppData\Local\Programs\Python\Python312\Lib\site-packages\ph4acmd2\__init__.py", line 51, in _start_controller
    self._start_reader()
  File "C:\Users\tgravran\AppData\Local\Programs\Python\Python312\Lib\site-packages\ph4acmd2\__init__.py", line 80, in _start_reader
    self.reset_reader()
  File "C:\Users\tgravran\AppData\Local\Programs\Python\Python312\Lib\site-packages\ph4acmd2\__init__.py", line 86, in reset_reader
    self.loop.add_reader(self.stdin.fileno(), self.reader)
  File "C:\Users\tgravran\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 538, in add_reader
    raise NotImplementedError
NotImplementedError
```

**Comment by ph4r05** [comment]
Thanks @jure123 for pointing this out. I will fix it in the code and release a new version

**Comment by dolomitt** [comment]
FYI I cannot get the main walkingpad source code to work on Windows. asyncio wont let me do add_reader anymore. 

[ProactorEventLoop](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.ProactorEventLoop) has the following limitations:
    The [loop.add_reader()](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.add_reader) and [loop.add_writer()](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.add_writer) methods are not supported.

I can get the source code from belt_control jupyter file to work though with my R1 Pro.

**Comment by ph4r05** [comment]
pls try now v1.0.2
