### ISSUE TITLE
ValueError: No address given to connect to

### ISSUE THREAD

**Issue by VitharMe** [ph4r05/ph4-walkingpad#9]
I am doing something wrong?

```
test@host:~/ph4-walkingpad $  ph4-walkingpad-ctl --stats 750 --json-file ~/walking.json -p profile.json
Traceback (most recent call last):
  File "/home/issa/.local/lib/python3.7/site-packages/ph4_walkingpad/main.py", line 374, in main
    await self.work()
  File "/home/issa/.local/lib/python3.7/site-packages/ph4_walkingpad/main.py", line 94, in work
    await self.connect(address)
  File "/home/issa/.local/lib/python3.7/site-packages/ph4_walkingpad/main.py", line 74, in connect
    await self.ctler.run()
  File "/home/issa/.local/lib/python3.7/site-packages/ph4_walkingpad/pad.py", line 359, in run
    await self.connect(address)
  File "/home/issa/.local/lib/python3.7/site-packages/ph4_walkingpad/pad.py", line 274, in connect
    raise ValueError('No address given to connect to')
ValueError: No address given to connect to
```
```
test@host:~/ph4-walkingpad $ cat profile.json
{
  "id": "xjfrac2lhj",
  "male": true,
  "age": 25,
  "weight": 70,
  "height": 1.80,
  "token": "tyJ5eXAiOoJKH1RiLCJh"
  "did": "57:4C:4D:4D:1B:1B",
  "email": "email@gmail.com",
  "password": "superpassword",
}
```

Token, did, email and pass are fake.

**Comment by ph4r05** [comment]
@VitharMe are you running it on OSX? If it is the case, please try the following https://github.com/ph4r05/ph4-walkingpad#osx-troubleshooting

**Comment by ph4r05** [comment]
Also, pls try running it with `--debug` parameter to get more logs

**Comment by ph4r05** [comment]
Closing for inactivity, pls reopen when the problem persists.
